name: unit-test
on:
  push:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Build with Maven
        working-directory: ./kaitai-shinsho
        run: ./mvnw clean jacoco:prepare-agent test jacoco:report
